[package]
name = "agc030"
version = "0.1.0"
authors = ["guchio3 <astt.hwhw@gmail.com>"]
edition = "2018"

# dependencies added to new project
[dependencies]
proconio = { version = "0.3.6", features = ["derive"] }

[profile.release]
lto = true
panic = 'abort'
